// Client-side building and signing for the plain BIP-84 chain.
//
// WHY THIS EXISTS. /api/v1/plain/spend takes the private keys for the addresses
// being spent, signs with them and returns the transaction. They are not stored
// and not logged, but they cross the network, and unlike a Silent Payments
// spend key they are whole keys on their own — whoever holds one can empty that
// address, with nothing else needed. spSign.ts removed that exposure from the
// Silent Payments path; this removes it from the other one.
//
// The device also derives the DESTINATION script here rather than taking the
// server's. Signing locally settles who holds the keys; it does not by itself
// settle where the money goes, and a client that signs whatever script it is
// handed is still paying whoever the server named. The plan's own script is
// compared against the one derived here and a disagreement stops the send.
//
// Second implementation of unrecoverable code, so it is checked the same way as
// spSign.ts — against vectors from the Python:
//   node scripts/check-plain-signing.mjs
// regenerated by siLNt helpers/_plain_signing_fixtures.py. These compare the
// finished transaction byte for byte, which the Silent Payments ones cannot:
// BIP-340 signing uses random aux data, while ECDSA here is RFC 6979 and
// deterministic, down to the low-R grinding both sides do.

import { secp256k1 } from '@noble/curves/secp256k1';
import { sha256 } from '@noble/hashes/sha256';
import { ripemd160 } from '@noble/hashes/ripemd160';
import { addressToScriptPubKey, p2wpkhProgram } from './btcAddress';
import { spOutputScript } from './spSign';

// Mirrors helpers/plain.py. A P2WPKH input is 68 vB (41 base + 27 witness); the
// overhead with a segwit marker is 10.5 vB; change is always P2WPKH at 31.
export const INPUT_VBYTES = 68;
export const OVERHEAD_VBYTES = 10.5;
export const CHANGE_VBYTES = 31;
export const DUST_SATS = 546;

const OUTPUT_VBYTES_BY_SCRIPT_LEN: Record<number, number> = {
  22: 31, // P2WPKH
  23: 32, // P2SH
  25: 34, // P2PKH
  34: 43, // P2WSH / P2TR
};

export function outputVbytes(scriptPubKey: Uint8Array): number {
  return OUTPUT_VBYTES_BY_SCRIPT_LEN[scriptPubKey.length] ?? 8 + 1 + scriptPubKey.length;
}

export interface PlainUtxo {
  txid: string;   // big-endian, as an explorer shows it
  vout: number;
  amount: number; // sats
  address: string;
}

export interface PlainBuiltTx {
  tx_hex: string;
  amount: number;
  change: number;
  fee: number;
  total_input: number;
  vsize: number;
  fee_rate_used: number;
  input_count: number;
  swept_addresses: string[];
  destination: string;
}

// ── bytes ────────────────────────────────────────────────────────────────────

function fromHex(s: string): Uint8Array {
  const clean = s.startsWith('0x') ? s.slice(2) : s;
  if (clean.length % 2) throw new Error('odd-length hex');
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(clean.substr(i * 2, 2), 16);
  return out;
}

function toHex(u8: Uint8Array): string {
  return Array.from(u8, (b) => b.toString(16).padStart(2, '0')).join('');
}

function concat(...parts: Uint8Array[]): Uint8Array {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let at = 0;
  for (const p of parts) {
    out.set(p, at);
    at += p.length;
  }
  return out;
}

function u32le(n: number): Uint8Array {
  const b = new Uint8Array(4);
  new DataView(b.buffer).setUint32(0, n >>> 0, true);
  return b;
}

function u64le(n: number): Uint8Array {
  // Two 32-bit writes rather than setBigUint64, which is not guaranteed on
  // Hermes — see spSign.ts.
  if (!Number.isSafeInteger(n) || n < 0) throw new Error(`amount out of range: ${n}`);
  const b = new Uint8Array(8);
  const dv = new DataView(b.buffer);
  dv.setUint32(0, n >>> 0, true);
  dv.setUint32(4, Math.floor(n / 0x100000000) >>> 0, true);
  return b;
}

function varint(n: number): Uint8Array {
  if (n < 0xfd) return new Uint8Array([n]);
  if (n <= 0xffff) return concat(new Uint8Array([0xfd]), u32le(n).slice(0, 2));
  return concat(new Uint8Array([0xfe]), u32le(n));
}

function dsha256(b: Uint8Array): Uint8Array {
  return sha256(sha256(b));
}

function hash160(b: Uint8Array): Uint8Array {
  return ripemd160(sha256(b));
}

function reversedTxid(txid: string): Uint8Array {
  return fromHex(txid).reverse();
}

// ── amounts ──────────────────────────────────────────────────────────────────

/**
 * Mirrors helpers/plain.py::plan_plain_spend's arithmetic.
 *
 * Deliberately a second implementation rather than a read of the plan: the
 * server quotes the fee and the change, and the signature commits to them, so
 * having no independent opinion would mean signing whatever was quoted.
 *
 * `amount` null means send everything and take the fee out of it.
 */
export function computePlainAmounts(
  utxos: PlainUtxo[],
  amount: number | null,
  feeRate: number,
  destinationVbytes: number,
) {
  if (!utxos.length) throw new Error('No confirmed coins on these addresses.');
  if (amount !== null && amount < DUST_SATS) {
    throw new Error(`Amount must be at least ${DUST_SATS} sats.`);
  }
  const totalInput = utxos.reduce((s, u) => s + u.amount, 0);
  let vsize = Math.ceil(
    OVERHEAD_VBYTES +
      INPUT_VBYTES * utxos.length +
      destinationVbytes +
      (amount !== null ? CHANGE_VBYTES : 0),
  );
  let fee = Math.max(1, Math.ceil(vsize * feeRate));

  let change = 0;
  let sendAmount: number;
  if (amount === null) {
    sendAmount = totalInput - fee;
    if (sendAmount < DUST_SATS) {
      throw new Error(
        `Would leave ${sendAmount} sats after a ${fee} sat fee, below the ` +
          `${DUST_SATS} sat dust limit. Wait for more coins or a lower fee rate.`,
      );
    }
  } else {
    sendAmount = amount;
    change = totalInput - amount - fee;
    if (change < 0) {
      throw new Error(
        `Not enough to cover ${amount} sats plus a ${fee} sat fee — these coins ` +
          `total ${totalInput} sats.`,
      );
    }
    if (change < DUST_SATS) {
      // Uneconomic to create; it goes to the miner and the transaction is one
      // output smaller than it was priced at.
      fee += change;
      change = 0;
      vsize -= CHANGE_VBYTES;
    }
  }
  return { totalInput, sendAmount, change, fee, vsize };
}

// ── transaction ──────────────────────────────────────────────────────────────

interface TxOut {
  value: number;
  script: Uint8Array;
}

/**
 * BIP-143 signature hash for one P2WPKH input, SIGHASH_ALL.
 *
 * Narrow on purpose, as in spSign.ts: every input on this chain is P2WPKH, so
 * the scriptCode is always the P2PKH equivalent of the witness program and
 * there is no other shape to handle.
 */
function segwitSighash(
  ins: PlainUtxo[],
  outs: TxOut[],
  index: number,
  program: Uint8Array,
): Uint8Array {
  const hashPrevouts = dsha256(
    concat(...ins.map((i) => concat(reversedTxid(i.txid), u32le(i.vout)))),
  );
  const hashSequence = dsha256(concat(...ins.map(() => u32le(0xffffffff))));
  const hashOutputs = dsha256(
    concat(...outs.map((o) => concat(u64le(o.value), varint(o.script.length), o.script))),
  );
  const scriptCode = concat(
    new Uint8Array([0x19, 0x76, 0xa9, 0x14]),
    program,
    new Uint8Array([0x88, 0xac]),
  );
  return dsha256(
    concat(
      u32le(2), // nVersion
      hashPrevouts,
      hashSequence,
      reversedTxid(ins[index].txid),
      u32le(ins[index].vout),
      scriptCode,
      u64le(ins[index].amount),
      u32le(0xffffffff), // nSequence
      hashOutputs,
      u32le(0), // nLockTime
      u32le(1), // SIGHASH_ALL
    ),
  );
}

/**
 * RFC 6979 with Bitcoin Core's low-R grinding, matching embit's
 * PrivateKey.sign(grind=True) byte for byte: retry with the counter as 32-byte
 * little-endian extra entropy until the DER encoding fits in 70 bytes.
 */
function signEcdsaGrind(sighash: Uint8Array, priv: Uint8Array): Uint8Array {
  let sig = secp256k1.sign(sighash, priv);
  let counter = 1;
  while (sig.toDERRawBytes().length > 70 && counter <= 200) {
    const extra = new Uint8Array(32);
    let v = counter;
    for (let i = 0; i < 32 && v > 0; i++) {
      extra[i] = v & 0xff;
      v = Math.floor(v / 256);
    }
    sig = secp256k1.sign(sighash, priv, { extraEntropy: extra });
    counter++;
  }
  return sig.toDERRawBytes();
}

/**
 * Build and sign a plain-chain spend, entirely on this device.
 *
 * The drop-in replacement for POST /api/v1/plain/spend: same result, no private
 * key on the wire. The transaction goes to /api/v1/plain/broadcast, which
 * already takes a tx_hex.
 *
 * `keys` maps each address being spent to its hex private key. Every coin must
 * have one — a partial spend would leave coins behind while telling the user
 * the address was emptied.
 */
export function buildSignedPlainTx(opts: {
  destination: string;
  utxos: PlainUtxo[];
  keys: Record<string, string>;
  amount: number | null; // null = send everything
  feeRate: number;
  changeAddress?: string | null;
  network: string;
  // The plan's own copy of the destination script, if there is one. Compared,
  // never used: a mismatch means this device and the server disagree about
  // where the money is going, and the only safe move is to stop.
  expectDestinationScriptHex?: string | null;
}): PlainBuiltTx {
  const { destination, utxos, keys, amount, feeRate, changeAddress, network } = opts;
  if (!utxos.length) throw new Error('No confirmed coins on these addresses.');

  const dest = (destination || '').trim();
  if (!dest) throw new Error('A destination is required.');

  // BIP-69, matching the server. Its plan already comes ordered; re-sorting
  // rather than trusting that keeps the two from silently diverging.
  const ins = [...utxos].sort((a, b) =>
    a.txid === b.txid ? a.vout - b.vout : a.txid < b.txid ? -1 : 1,
  );

  // One key per coin, checked against the address it is claimed to control. A
  // mismatch here is a wrong wallet or a stale derivation, and failing now beats
  // a signature the network rejects with nothing to point at.
  const signing = ins.map((u) => {
    const hex = keys[u.address];
    if (!hex) throw new Error(`No key on this device for ${u.address}.`);
    const priv = fromHex(hex);
    const pub = secp256k1.getPublicKey(priv, true);
    const program = p2wpkhProgram(u.address, network);
    if (toHex(hash160(pub)) !== toHex(program)) {
      throw new Error(
        `The key for ${u.address} does not control it — re-import the wallet on ` +
          `this device.`,
      );
    }
    return { priv, pub, program };
  });

  const isSp = dest.startsWith('sp1') || dest.startsWith('tsp1');
  // Every input is P2WPKH, so every key contributes UNNEGATED. See
  // spSign.ts::spOutputScript — getting that flag wrong produces an output the
  // recipient's scanner will never find.
  const destScript = isSp
    ? spOutputScript(dest, signing.map((s) => s.priv), ins, false)
    : addressToScriptPubKey(dest, network);

  if (opts.expectDestinationScriptHex && !isSp) {
    if (toHex(destScript) !== opts.expectDestinationScriptHex.toLowerCase()) {
      throw new Error(
        `Refusing to send: the server resolved ${dest} to a different output ` +
          `than this device did. Nothing has been signed.`,
      );
    }
  }

  const { totalInput, sendAmount, change, fee, vsize } = computePlainAmounts(
    ins, amount, feeRate, outputVbytes(destScript),
  );

  const outs: TxOut[] = [{ value: sendAmount, script: destScript }];
  if (change) {
    if (!changeAddress) {
      throw new Error('A change address is required when not sending everything.');
    }
    // Derived here, not taken from the plan: change comes back to this wallet's
    // own chain, so the device is the authority on where.
    outs.push({ value: change, script: addressToScriptPubKey(changeAddress, network) });
    // Do not leak which output is change by its position.
    outs.sort((a, b) => a.value - b.value || (toHex(a.script) < toHex(b.script) ? -1 : 1));
  }

  const witnesses = signing.map((s, i) => {
    const sig = signEcdsaGrind(segwitSighash(ins, outs, i, s.program), s.priv);
    const sigWithType = concat(sig, new Uint8Array([0x01])); // SIGHASH_ALL
    return concat(
      varint(2),
      varint(sigWithType.length),
      sigWithType,
      varint(s.pub.length),
      s.pub,
    );
  });

  const signed = concat(
    u32le(2),
    new Uint8Array([0x00, 0x01]), // segwit marker + flag
    varint(ins.length),
    ...ins.map((i) =>
      concat(reversedTxid(i.txid), u32le(i.vout), varint(0), u32le(0xffffffff)),
    ),
    varint(outs.length),
    ...outs.map((o) => concat(u64le(o.value), varint(o.script.length), o.script)),
    ...witnesses,
    u32le(0),
  );

  return {
    tx_hex: toHex(signed),
    amount: sendAmount,
    change,
    fee,
    total_input: totalInput,
    vsize,
    fee_rate_used: feeRate,
    input_count: ins.length,
    swept_addresses: Array.from(new Set(ins.map((u) => u.address))).sort(),
    destination: dest,
  };
}

/** Exposed for the cross-check runner; not part of the sending path. */
export const __testing = {
  computePlainAmounts,
  segwitSighash,
  signEcdsaGrind,
  outputVbytes,
  hash160,
  toHex,
  fromHex,
};
